spring.application.name=SE2034-JV_ThanhDHHE194260_CarRentingSystem
server.port=8080 
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarRentingSystem_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html